[package]
name = "antigrav"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1.0.128"
spacenav-plus = "0.1.1"
tungstenite = "0.24.0"
tokio-tungstenite = "0.23.1"
tokio = { version = "1.40.0", features = ["full", "sync"] }
futures = "0.3.30"
futures-util = "0.3.30"
